version: '3.9'
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - "${PROJECT_ROOT_PATH:-./app}:/app"
    ports:
      - "${NGINX_HOST_PORT:-80}:80"
    depends_on:
      - php-fpm
    networks:
      - systemeio-net
  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    volumes:
      - "${PROJECT_ROOT_PATH:-./app}:/app"
    depends_on:
      - postgres
    networks:
      - systemeio-net
  php-cli:
    build:
      context: docker/php-cli
      dockerfile: Dockerfile
    user: www-data
    volumes:
      - "${PROJECT_ROOT_PATH:-./app}:/app"
    environment:
      - "COMPOSER_ALLOW_SUPERUSER=1"
    depends_on:
      - postgres
    tty: true
    networks:
      - systemeio-net
  postgres:
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    volumes:
      - systemeio-pgsql:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
      - "POSTGRES_USER=${DB_USERNAME}"
      - "POSTGRES_DB=${DB_NAME}"
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    networks:
      - systemeio-net
volumes:
  systemeio-pgsql:
networks:
  systemeio-net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.95.0/24"
