api_platform:
    title: Systemeio API
    version: 0.0.1
    formats:
        json: ['application/json']
    swagger:
        versions: [ 3 ]
    docs_formats:
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    event_listeners_backward_compatibility_layer: false
    keep_legacy_inflector: false
    enable_re_doc: false
    graphql:
        graphiql:
            enabled: false
    exception_to_status:
        # Validation exception
        ApiPlatform\Validator\Exception\ValidationException: 400
        # Payment exception
        Exception: 400